# Generated by Django 5.0 on 2024-04-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='help',
        ),
        migrations.RemoveField(
            model_name='images',
            name='status',
        ),
        migrations.AddField(
            model_name='help',
            name='status',
            field=models.IntegerField(choices=[(-1, '已完成'), (0, '进行中'), (1, '未完成')], default=1),
        ),
    ]
