# Generated by Django 5.0 on 2024-05-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_rename_post_images_help_remove_images_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='contact_info',
            field=models.TextField(blank=True, default=None),
        ),
    ]
