# Generated by Django 5.0 on 2024-05-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_images_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='help',
            name='contact_info',
            field=models.TextField(blank=True, default=None),
        ),
    ]
