# Generated by Django 5.0 on 2024-04-11 01:50

import django.db.models.deletion
import goods.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=goods.models.default_image_path, null=True, upload_to='static/goods_pics/')),
                ('description', models.TextField(blank=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='goods.goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='helps', to='goods.images'),
        ),
    ]
