# Generated by Django 5.0 on 2024-04-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='number',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='goods',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
