# Generated by Django 5.0 on 2024-05-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goods_number_remove_shoppingcart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='contact_info',
            field=models.TextField(blank=True, default=None),
        ),
    ]
