# Generated by Django 5.0 on 2024-04-11 01:15

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default=activity.models.default_image_path, null=True, upload_to='static/activity_img/'),
        ),
    ]
