# Generated by Django 5.0 on 2024-04-09 04:34

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pic',
            field=models.ImageField(blank=True, default=user.models.default_avatar_path, null=True, upload_to='static/user_pics/'),
        ),
    ]
