# Generated by Django 5.0 on 2024-04-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userinfo_friends_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
