# Generated by Django 5.0 on 2024-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
