# Generated by Django 5.0 on 2024-05-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userinfo_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='contact_info',
        ),
    ]
